# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 02156f10f38c6b0980bed633cb0e546c30c8f9d48eebcdb49017b668bfb4a2a7e145fd811342d2b5523647e8af157bb0e88e55dd60a4ba03b201026a6f720791

test:
  secret_key_base: ebc95c9f0597137e4d114cd33c86695529f4cf46a78f162709af96eb048f02986d82ce2cb3ed51300f1b0ee12d0f42eb03b4c3433f8a0704962e88891ec28d2a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
